# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250904-160835-simple-gravity

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: True


policies:
  # The RulePolicy handles the rules defined in rules.yml.
  # It prioritizes these single-turn, predictable interactions.
  - name: RulePolicy

  # The MemoizationPolicy remembers past conversation turns and can reproduce
  # them exactly. It is very fast and efficient for "happy path" scenarios.
  - name: MemoizationPolicy

  # The TEDPolicy (Transformer Embedding Dialogue) is a powerful neural network
  # policy that can learn from your stories. It's great for handling complex
  # and unseen conversational turns.
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
